name = "GasModels"
uuid = "5e113713-6c35-5477-b766-e1109486666f"
authors = ["Russell Bent <rbent@lanl.gov>", "Kaarthik Sundar <kaarthik@lanl.gov>"]
repo = "https://github.com/lanl-ansi/GasModels.jl.git"
version = "0.5.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"

[compat]
Cbc = ">= 0.4"
InfrastructureModels = "~0.2, ~0.3"
Ipopt = ">= 0.4"
JSON = ">= 0.18.0"
JuMP = "~0.19.1, ~0.20"
Juniper = ">= 0.4"
MathOptInterface = "~0.8.4, ~0.9"
Memento = "~0.10, ~0.11, ~0.12"
julia = "~1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Ipopt", "Juniper", "Cbc", "Test"]
